"""initial_schema

Revision ID: abcd0b71c7eb
Revises: 
Create Date: 2026-04-18 07:18:57.464623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
import geoalchemy2.types

# revision identifiers, used by Alembic.
revision: str = 'abcd0b71c7eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('firebase_uid', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.Text(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("preferred_language IN ('en','hi','gu')", name=op.f('ck_users_users_preferred_language_check')),
    sa.CheckConstraint("role IN ('volunteer','coordinator','admin')", name=op.f('ck_users_users_role_check')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_users_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('firebase_uid', name=op.f('uq_users_firebase_uid'))
    )
    op.create_index('idx_users_firebase_uid', 'users', ['firebase_uid'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_ip', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('idx_audit_actor_time', 'audit_log', ['actor_user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recurrence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_availability_slots_availability_slots_end_after_start_check')),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], name=op.f('fk_availability_slots_volunteer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_slots'))
    )
    op.create_index('idx_avail_volunteer_range', 'availability_slots', ['volunteer_id', 'start_time', 'end_time'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_entity_type', sa.Text(), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('email','in_app')", name=op.f('ck_notifications_notifications_channel_check')),
    sa.CheckConstraint("status IN ('queued','sent','delivered','failed','read')", name=op.f('ck_notifications_notifications_status_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notif_user_status', 'notifications', ['user_id', 'status', sa.text('created_at DESC')], unique=False)
    op.create_table('raw_submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitter_phone', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'received'"), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('extracted_need_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source IN ('webform','email','api')", name=op.f('ck_raw_submissions_raw_submissions_source_check')),
    sa.CheckConstraint("status IN ('received','processing','extracted','failed','discarded')", name=op.f('ck_raw_submissions_raw_submissions_status_check')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_raw_submissions_submitted_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_submissions'))
    )
    op.create_index('idx_raw_status', 'raw_submissions', ['status', 'created_at'], unique=False)
    op.create_table('volunteer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::TEXT[]"), nullable=False),
    sa.Column('skills_text', sa.Text(), nullable=True),
    sa.Column('skills_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('home_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('home_address', sa.Text(), nullable=True),
    sa.Column('max_travel_km', sa.Integer(), server_default=sa.text('20'), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('verification_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reliability_score', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('total_tasks_completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_tasks_declined', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text(r"""'{"email"\:true,"in_app"\:true}'::JSONB"""), nullable=False),
    sa.Column('email_deliverable', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_travel_km BETWEEN 1 AND 200', name=op.f('ck_volunteer_profiles_volunteer_profiles_max_travel_km_check')),
    sa.CheckConstraint('reliability_score BETWEEN 0 AND 1', name=op.f('ck_volunteer_profiles_volunteer_profiles_reliability_score_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_volunteer_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_volunteer_profiles'))
    )
    op.create_index('idx_vp_active_verified', 'volunteer_profiles', ['active', 'verified'], unique=False, postgresql_where=sa.text('active = TRUE'))
    op.create_index('idx_vp_home_location', 'volunteer_profiles', ['home_location'], unique=False, postgresql_using='gist')
    op.create_index('idx_vp_skills_embedding', 'volunteer_profiles', ['skills_embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'skills_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 10})
    op.create_table('needs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('raw_submission_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('need_type', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_original', sa.Text(), nullable=True),
    sa.Column('original_language', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Text(), nullable=False),
    sa.Column('beneficiary_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('required_team_size', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('resources_needed', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending_review'"), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_review','published','matching_complete','assigned','in_progress','completed','cancelled','expired')", name=op.f('ck_needs_needs_status_check')),
    sa.CheckConstraint("urgency IN ('critical','high','medium','low')", name=op.f('ck_needs_needs_urgency_check')),
    sa.CheckConstraint('beneficiary_count >= 0', name=op.f('ck_needs_needs_beneficiary_count_check')),
    sa.CheckConstraint('required_team_size >= 1', name=op.f('ck_needs_needs_required_team_size_check')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_needs_created_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_needs_org_id_orgs')),
    sa.ForeignKeyConstraint(['raw_submission_id'], ['raw_submissions.id'], name=op.f('fk_needs_raw_submission_id_raw_submissions')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_needs_reviewed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_needs'))
    )
    op.create_index('idx_needs_embedding', 'needs', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 10})
    op.create_index('idx_needs_status_priority', 'needs', ['status', sa.text('priority_score DESC')], unique=False)
    op.create_index('idx_needs_urgency_deadline', 'needs', ['urgency', 'deadline'], unique=False, postgresql_where=sa.text("status = 'published'"))
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('need_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('role_in_team', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending_accept'"), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accept_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coordinator_rating', sa.Integer(), nullable=True),
    sa.Column('volunteer_feedback', sa.Text(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completion_photo_urls', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending_accept','accepted','declined','in_progress','completed','cancelled','no_show','expired')", name=op.f('ck_assignments_assignments_status_check')),
    sa.CheckConstraint('coordinator_rating BETWEEN 1 AND 5', name=op.f('ck_assignments_assignments_coordinator_rating_check')),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], name=op.f('fk_assignments_need_id_needs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], name=op.f('fk_assignments_volunteer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments')),
    sa.UniqueConstraint('need_id', 'volunteer_id', name='uq_assignments_need_volunteer')
    )
    op.create_index('idx_assign_need', 'assignments', ['need_id'], unique=False)
    op.create_index('idx_assign_pending_deadline', 'assignments', ['accept_deadline'], unique=False, postgresql_where=sa.text("status = 'pending_accept'"))
    op.create_index('idx_assign_volunteer_recent', 'assignments', ['volunteer_id', sa.text('assigned_at DESC')], unique=False)
    op.create_index('idx_assign_volunteer_status', 'assignments', ['volunteer_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assign_volunteer_status', table_name='assignments')
    op.drop_index('idx_assign_volunteer_recent', table_name='assignments')
    op.drop_index('idx_assign_pending_deadline', table_name='assignments', postgresql_where=sa.text("status = 'pending_accept'"))
    op.drop_index('idx_assign_need', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('idx_needs_urgency_deadline', table_name='needs', postgresql_where=sa.text("status = 'published'"))
    op.drop_index('idx_needs_status_priority', table_name='needs')
    op.drop_index('idx_needs_embedding', table_name='needs', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 10})
    op.drop_table('needs')
    op.drop_index('idx_vp_skills_embedding', table_name='volunteer_profiles', postgresql_using='ivfflat', postgresql_ops={'skills_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 10})
    op.drop_index('idx_vp_home_location', table_name='volunteer_profiles', postgresql_using='gist')
    op.drop_index('idx_vp_active_verified', table_name='volunteer_profiles', postgresql_where=sa.text('active = TRUE'))
    op.drop_table('volunteer_profiles')
    op.drop_index('idx_raw_status', table_name='raw_submissions')
    op.drop_table('raw_submissions')
    op.drop_index('idx_notif_user_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_avail_volunteer_range', table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_actor_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_users_role', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_users_firebase_uid', table_name='users')
    op.drop_table('users')
    op.drop_table('orgs')
    # ### end Alembic commands ###
